/**/controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/arm_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0
      J1: { trajectory: 0.2, goal: 0.02 }
      J2: { trajectory: 0.2, goal: 0.02 }
      J3: { trajectory: 0.2, goal: 0.02 }
      J4: { trajectory: 0.2, goal: 0.02 }
      J5: { trajectory: 0.2, goal: 0.02 }
      J6: { trajectory: 0.2, goal: 0.02 }

    gains: # Required because we're controlling a velocity interface
      J1: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 } # Smaller 'p' term, since ff term does most of the work
      J2: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
      J3: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
      J4: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
      J5: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
      J1: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }

    velocity_ff:
      J1: 1.0
      J2: 1.0
      J3: 1.0
      J4: 1.0
      J5: 1.0
      J6: 1.0